resources:
  - ../rewrite
patches:
  - target:
      kind: Deployment
      name: if-codex-worker
    patch: |-
      - op: add
        path: /spec/template/spec/imagePullSecrets
        value:
          - name: ecr-registry
  - target:
      kind: PersistentVolumeClaim
      name: if-codex-login
    patch: |-
      - op: replace
        path: /metadata/name
        value: if-codex-login-laptop
  - target:
      kind: Deployment
      name: if-codex-worker
    patch: |-
      - op: add
        path: /spec/template/spec/nodeSelector
        value:
          if.codex/worker: laptop
      - op: replace
        path: /spec/template/spec/volumes/0/persistentVolumeClaim/claimName
        value: if-codex-login-laptop
  - target:
      kind: PersistentVolumeClaim
      name: if-codex-state
    patch: |-
      - op: replace
        path: /metadata/name
        value: if-codex-state-laptop
  - target:
      kind: Deployment
      name: if-codex-worker
    patch: |-
      - op: replace
        path: /spec/template/spec/volumes/1/persistentVolumeClaim/claimName
        value: if-codex-state-laptop
images:
  - name: if-codex-worker
    newName: 429310424269.dkr.ecr.ca-central-1.amazonaws.com/if-agent-api
    digest: sha256:ca816dfdbe7b6083d55adb61c5123434d7de28c7b10d7affb805d43f010c5636
