"""File serving endpoints for attachments.

GET /files/sandbox/{conversation_id}/{filepath} - Serve files from legacy sandbox (deprecated).
GET /files/workspace/{chat_id}/{filepath} - Serve files from Docker named volumes (Part5).
"""
import hashlib
import logging
import os
from pathlib import Path
from typing import Optional

from fastapi import APIRouter, HTTPException
from fastapi.responses import FileResponse

from config import SANDBOX_PATH, TERMINAL_VOLUME_HOST_ROOT

router = APIRouter()
logger = logging.getLogger(__name__)


def get_sandbox_directory() -> Path:
    """Get the sandbox root directory path, creating it if needed.
    
    Returns:
        Path to the sandbox root directory
    """
    sandbox = Path(SANDBOX_PATH)
    sandbox.mkdir(parents=True, exist_ok=True)
    return sandbox


def get_conversation_sandbox(conversation_id: str) -> Path:
    """Get the sandbox directory for a specific conversation.
    
    Args:
        conversation_id: Unique conversation identifier
        
    Returns:
        Path to the conversation's sandbox directory
    """
    sandbox = Path(SANDBOX_PATH) / conversation_id
    sandbox.mkdir(parents=True, exist_ok=True)
    return sandbox


@router.get("/files/sandbox/{conversation_id}/{filepath:path}")
async def serve_sandbox_file(conversation_id: str, filepath: str):
    """Serve a file from a conversation's sandbox directory.
    
    This endpoint serves files generated by the agent (code files, diagrams, etc.)
    as static files that can be downloaded by clients.
    
    Args:
        conversation_id: Unique conversation identifier
        filepath: Relative path to the file within the conversation's sandbox
        
    Returns:
        FileResponse with the file content
        
    Raises:
        HTTPException: If file not found or access denied
    """
    sandbox_dir = get_conversation_sandbox(conversation_id)
    
    # Construct full file path
    file_path = sandbox_dir / filepath
    
    # Security check: ensure the path is within sandbox (prevent path traversal)
    try:
        file_path = file_path.resolve()
        sandbox_dir = sandbox_dir.resolve()
        
        if not str(file_path).startswith(str(sandbox_dir)):
            raise HTTPException(
                status_code=403,
                detail="Access denied: path traversal denied"
            )
    except Exception:
        raise HTTPException(
            status_code=400,
            detail="Invalid file path"
        )
    
    # Check if file exists
    if not file_path.exists():
        raise HTTPException(
            status_code=404,
            detail=f"File not found: {filepath}"
        )
    
    # Check if it's a file (not a directory)
    if not file_path.is_file():
        raise HTTPException(
            status_code=400,
            detail=f"Not a file: {filepath}"
        )
    
    # Determine content type based on file extension
    content_type = get_content_type(file_path.suffix)
    
    return FileResponse(
        path=file_path,
        media_type=content_type,
        filename=file_path.name
    )


def _hash8(chat_id: str) -> str:
    """Generate 8-character hash from chat_id for volume name.
    
    Args:
        chat_id: Chat/conversation identifier
        
    Returns:
        8-character hex string
    """
    return hashlib.sha256(chat_id.encode()).hexdigest()[:8]


@router.get("/files/workspace/{chat_id}/{filepath:path}")
async def serve_workspace_file(chat_id: str, filepath: str):
    """Serve a file from a Docker named volume workspace.
    
    Part5: Serves files from the persistent terminal container workspaces.
    Files are stored in named Docker volumes at /var/lib/docker/volumes/if-ws-{hash8}/_data/
    
    Args:
        chat_id: Chat/conversation identifier (used to derive volume name)
        filepath: Relative path to the file within the workspace
        
    Returns:
        FileResponse with the file content
        
    Raises:
        HTTPException: If file not found, access denied, or volume host access disabled
    """
    # Check if volume host access is configured
    if not TERMINAL_VOLUME_HOST_ROOT:
        raise HTTPException(
            status_code=501,
            detail="Workspace file serving requires TERMINAL_VOLUME_HOST_ROOT configuration"
        )
    
    # Path traversal protection
    normalized = os.path.normpath(filepath)
    if normalized.startswith("..") or normalized.startswith("/"):
        raise HTTPException(
            status_code=403,
            detail="Access denied: path traversal denied"
        )
    
    # Compute volume name from chat_id
    suffix = _hash8(chat_id)
    volume_name = f"if-ws-{suffix}"
    
    # Construct full path to file in Docker volume
    # Docker named volumes store data at /var/lib/docker/volumes/{name}/_data/
    volume_path = Path(TERMINAL_VOLUME_HOST_ROOT) / volume_name / "_data"
    full_path = volume_path / normalized
    
    # Additional security check: ensure resolved path is within volume
    try:
        full_path = full_path.resolve()
        volume_path = volume_path.resolve()
        
        if not str(full_path).startswith(str(volume_path)):
            raise HTTPException(
                status_code=403,
                detail="Access denied: path escapes volume"
            )
    except Exception as e:
        logger.warning(f"[Workspace] Path resolution error: {e}")
        raise HTTPException(
            status_code=400,
            detail="Invalid file path"
        )
    
    # Check if file exists
    if not full_path.exists():
        raise HTTPException(
            status_code=404,
            detail=f"File not found: {filepath}"
        )
    
    # Check if it's a file (not a directory)
    if not full_path.is_file():
        raise HTTPException(
            status_code=400,
            detail=f"Not a file: {filepath}"
        )
    
    # Determine content type based on file extension
    content_type = get_content_type(full_path.suffix)
    
    logger.info(f"[Workspace] Serving file: {full_path} for chat_id: {chat_id}")
    
    return FileResponse(
        path=full_path,
        media_type=content_type,
        filename=full_path.name
    )


def get_content_type(extension: str) -> Optional[str]:
    """Get MIME type for a file extension.
    
    Args:
        extension: File extension (with dot, e.g., ".py")
        
    Returns:
        MIME type string or None for default handling
    """
    extension = extension.lower()
    
    # Supported attachment types per plan.md
    content_types = {
        # Code (general)
        ".py": "text/x-python",
        ".ts": "text/typescript",
        ".js": "text/javascript",
        ".jsx": "text/javascript",
        ".tsx": "text/typescript",
        ".go": "text/x-go",
        ".rs": "text/x-rust",
        ".rb": "text/x-ruby",
        ".java": "text/x-java",
        ".c": "text/x-c",
        ".cpp": "text/x-c++",
        ".cs": "text/x-csharp",
        ".swift": "text/x-swift",
        ".kt": "text/x-kotlin",
        
        # IaC / DevOps
        ".tf": "text/x-terraform",
        ".hcl": "text/x-hcl",
        ".yaml": "text/yaml",
        ".yml": "text/yaml",
        ".json": "application/json",
        ".toml": "text/x-toml",
        ".tfvars": "text/x-terraform",
        
        # Config
        ".env.example": "text/plain",
        ".ini": "text/x-ini",
        ".cfg": "text/x-config",
        ".conf": "text/plain",
        ".properties": "text/x-java-properties",
        ".xml": "application/xml",
        
        # Shell
        ".sh": "text/x-shellscript",
        ".bash": "text/x-shellscript",
        ".zsh": "text/x-shellscript",
        ".ps1": "text/x-powershell",
        ".bat": "text/x-bat",
        
        # Documents
        ".md": "text/markdown",
        ".txt": "text/plain",
        ".pdf": "application/pdf",
        ".rst": "text/x-rst",
        ".adoc": "text/x-asciidoc",
        
        # Images
        ".png": "image/png",
        ".svg": "image/svg+xml",
        ".jpg": "image/jpeg",
        ".jpeg": "image/jpeg",
        ".webp": "image/webp",
        ".drawio": "application/xml",
        
        # Audio
        ".mp3": "audio/mpeg",
        ".wav": "audio/wav",
        ".ogg": "audio/ogg",
        
        # Data
        ".csv": "text/csv",
        ".parquet": "application/octet-stream",
        ".sql": "text/x-sql",
    }
    
    return content_types.get(extension)
