"""File serving endpoints for attachments.

GET /files/sandbox/{filepath} - Serve files generated by the agent.
"""
import os
from pathlib import Path
from typing import Optional

from fastapi import APIRouter, HTTPException
from fastapi.responses import FileResponse

from config import SANDBOX_PATH

router = APIRouter()


def get_sandbox_directory() -> Path:
    """Get the sandbox directory path, creating it if needed.
    
    Returns:
        Path to the sandbox directory
    """
    sandbox = Path(SANDBOX_PATH)
    sandbox.mkdir(parents=True, exist_ok=True)
    return sandbox


@router.get("/files/sandbox/{filepath:path}")
async def serve_sandbox_file(filepath: str):
    """Serve a file from the sandbox directory.
    
    This endpoint serves files generated by the agent (code files, diagrams, etc.)
    as static files that can be downloaded by clients.
    
    Args:
        filepath: Relative path to the file within the sandbox
        
    Returns:
        FileResponse with the file content
        
    Raises:
        HTTPException: If file not found or access denied
    """
    sandbox_dir = get_sandbox_directory()
    
    # Construct full file path
    file_path = sandbox_dir / filepath
    
    # Security check: ensure the path is within sandbox
    try:
        file_path = file_path.resolve()
        sandbox_dir = sandbox_dir.resolve()
        
        if not str(file_path).startswith(str(sandbox_dir)):
            raise HTTPException(
                status_code=403,
                detail="Access denied: path outside sandbox"
            )
    except Exception:
        raise HTTPException(
            status_code=400,
            detail="Invalid file path"
        )
    
    # Check if file exists
    if not file_path.exists():
        raise HTTPException(
            status_code=404,
            detail=f"File not found: {filepath}"
        )
    
    # Check if it's a file (not a directory)
    if not file_path.is_file():
        raise HTTPException(
            status_code=400,
            detail=f"Not a file: {filepath}"
        )
    
    # Determine content type based on file extension
    content_type = get_content_type(file_path.suffix)
    
    return FileResponse(
        path=file_path,
        media_type=content_type,
        filename=file_path.name
    )


def get_content_type(extension: str) -> Optional[str]:
    """Get MIME type for a file extension.
    
    Args:
        extension: File extension (with dot, e.g., ".py")
        
    Returns:
        MIME type string or None for default handling
    """
    extension = extension.lower()
    
    # Supported attachment types per plan.md
    content_types = {
        # Code (general)
        ".py": "text/x-python",
        ".ts": "text/typescript",
        ".js": "text/javascript",
        ".jsx": "text/javascript",
        ".tsx": "text/typescript",
        ".go": "text/x-go",
        ".rs": "text/x-rust",
        ".rb": "text/x-ruby",
        ".java": "text/x-java",
        ".c": "text/x-c",
        ".cpp": "text/x-c++",
        ".cs": "text/x-csharp",
        ".swift": "text/x-swift",
        ".kt": "text/x-kotlin",
        
        # IaC / DevOps
        ".tf": "text/x-terraform",
        ".hcl": "text/x-hcl",
        ".yaml": "text/yaml",
        ".yml": "text/yaml",
        ".json": "application/json",
        ".toml": "text/x-toml",
        ".tfvars": "text/x-terraform",
        
        # Config
        ".env.example": "text/plain",
        ".ini": "text/x-ini",
        ".cfg": "text/x-config",
        ".conf": "text/plain",
        ".properties": "text/x-java-properties",
        ".xml": "application/xml",
        
        # Shell
        ".sh": "text/x-shellscript",
        ".bash": "text/x-shellscript",
        ".zsh": "text/x-shellscript",
        ".ps1": "text/x-powershell",
        ".bat": "text/x-bat",
        
        # Documents
        ".md": "text/markdown",
        ".txt": "text/plain",
        ".pdf": "application/pdf",
        ".rst": "text/x-rst",
        ".adoc": "text/x-asciidoc",
        
        # Images
        ".png": "image/png",
        ".svg": "image/svg+xml",
        ".jpg": "image/jpeg",
        ".jpeg": "image/jpeg",
        ".webp": "image/webp",
        ".drawio": "application/xml",
        
        # Audio
        ".mp3": "audio/mpeg",
        ".wav": "audio/wav",
        ".ogg": "audio/ogg",
        
        # Data
        ".csv": "text/csv",
        ".parquet": "application/octet-stream",
        ".sql": "text/x-sql",
    }
    
    return content_types.get(extension)
